type Query {
  getGames: [Game]
}
type Mutation {
  createGame(game: NewGameInput!): Game
  editGame(id:ID!,game: EditGameInput!): String
}
type Game {
  _id: ID!
  title: String!
  developers: [Developer]
}

input NewGameInput {
  title: String!
  developers: [String!]!
}

input EditGameInput {
  title: String
  developers: [String!]
}